import { Droplets, Leaf, Info } from 'lucide-react';
import { Modal } from '../Modal';
import { cn } from '@/utils';

export interface EnvironmentalImpactModalProps {
  isOpen?: boolean;
  onClose?: () => void;
  environmentalImpact: {
    totalCo2SavingsKG: number;
    totalWaterSavingsLT: number;
    materialBreakdown: Array<{
      materialType: string;
      percentage: number;
      weightKG: number;
      co2SavingsKG: number;
      waterSavingsLT: number;
    }>;
  };

  // Labels
  co2SavingsTitle?: string;
  waterSavingsTitle?: string;
  weightLabel?: string;
  co2SavingsLabel?: string;
  waterSavingsLabel?: string;
  materialBreakdownLabel?: string;
  co2EquivalenceLabel?: string;
  waterEquivalenceLabel?: string;
  infoText?: string;
  carDistanceLabel?: string;
  showerCountLabel?: string;
}

export default function EnvironmentalImpactModal({
  isOpen,
  onClose,
  environmentalImpact,

  // Labels
  co2SavingsTitle = 'CO₂ Savings',
  waterSavingsTitle = 'Water Savings',
  weightLabel = 'Weight',
  co2SavingsLabel = 'CO₂ Saved',
  waterSavingsLabel = 'Water Saved',
  materialBreakdownLabel = 'Material Breakdown',
  carDistanceLabel = ' by car',
  showerCountLabel = ' showers',
  co2EquivalenceLabel = 'Equivalent to',
  waterEquivalenceLabel = 'Equivalent to',
  infoText = 'These values are estimates based on the savings generated by reusing products instead of manufacturing new ones. The calculations consider the average impact of producing each material.',
}: EnvironmentalImpactModalProps) {
  const formatNumber = (num: number) => {
    return new Intl.NumberFormat('es-CL', {
      minimumFractionDigits: 1,
      maximumFractionDigits: 1,
    }).format(num);
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Impacto Ambiental Detallado"
      size="md"
    >
      <div className="space-y-6">
        {/* Environmental Savings Summary */}
        <div className={cn('flex flex-col md:flex-row', 'gap-4 md:gap-6')}>
          <div
            className={cn(
              'bg-success/10 dark:bg-success/20',
              'rounded-lg',
              'p-4',
              'flex-1'
            )}
          >
            <div className={cn('flex items-center', 'gap-2', 'mb-2')}>
              <Leaf className="w-5 h-5 text-success" />
              <span
                className={cn(
                  'text-sm font-medium text-text-muted',
                  'dark:text-stone-400'
                )}
              >
                {co2SavingsTitle}
              </span>
            </div>
            <p className={cn('text-2xl font-bold text-success')}>
              {formatNumber(environmentalImpact.totalCo2SavingsKG)} kg
            </p>
            <p
              className={cn(
                'text-xs text-text-muted',
                'dark:text-stone-400',
                'mt-1'
              )}
            >
              {co2EquivalenceLabel}{' '}
              {formatNumber(environmentalImpact.totalCo2SavingsKG * 4.5)} km
              {carDistanceLabel}
            </p>
          </div>

          <div
            className={cn(
              'bg-info/10',
              'dark:bg-info/20',
              'rounded-lg',
              'p-4',
              'flex-1'
            )}
          >
            <div className={cn('flex', 'items-center', 'gap-2', 'mb-2')}>
              <Droplets className="w-5 h-5 text-info" />
              <span
                className={cn(
                  'text-sm',
                  'font-medium',
                  'text-text-muted',
                  'dark:text-stone-400'
                )}
              >
                {waterSavingsTitle}
              </span>
            </div>
            <p className={cn('text-2xl', 'font-bold', 'text-info')}>
              {formatNumber(environmentalImpact.totalWaterSavingsLT)} L
            </p>
            <p
              className={cn(
                'text-xs',
                'text-text-muted',
                'dark:text-stone-400',
                'mt-1'
              )}
            >
              {waterEquivalenceLabel}{' '}
              {formatNumber(environmentalImpact.totalWaterSavingsLT / 8)}{' '}
              {showerCountLabel}
            </p>
          </div>
        </div>

        {/* Material Breakdown */}
        {environmentalImpact.materialBreakdown.length > 0 && (
          <div>
            <h3
              className={cn(
                'text-lg',
                'font-bold',
                'text-text-primary',
                'dark:text-stone-100',
                'mb-4',
                'flex',
                'items-center',
                'gap-2'
              )}
            >
              <Info className="w-5 h-5" />
              {materialBreakdownLabel}
            </h3>

            <div className={cn('space-y-3')}>
              {environmentalImpact.materialBreakdown.map((material, index) => (
                <div
                  key={index}
                  className={cn(
                    'border',
                    'border-neutral/20',
                    'dark:border-stone-700',
                    'rounded-lg',
                    'p-4',
                    'hover:bg-neutral/5',
                    'dark:hover:bg-stone-800/50',
                    'transition-colors'
                  )}
                >
                  <div
                    className={cn(
                      'flex',
                      'items-center',
                      'justify-between',
                      'mb-3'
                    )}
                  >
                    <h4
                      className={cn(
                        'font-semibold',
                        'text-text-primary',
                        'dark:text-stone-100'
                      )}
                    >
                      {material.materialType}
                    </h4>
                    <span
                      className={cn('text-lg', 'font-bold', 'text-primary')}
                    >
                      {material.percentage.toFixed(1)}%
                    </span>
                  </div>

                  <div
                    className={cn('grid', 'grid-cols-3', 'gap-3', 'text-sm')}
                  >
                    <div>
                      <p
                        className={cn(
                          'text-xs',
                          'text-text-muted',
                          'dark:text-stone-400',
                          'mb-1'
                        )}
                      >
                        {weightLabel}
                      </p>
                      <p
                        className={cn(
                          'font-semibold',
                          'text-text-secondary',
                          'dark:text-stone-300'
                        )}
                      >
                        {formatNumber(material.weightKG)} kg
                      </p>
                    </div>
                    <div>
                      <p
                        className={cn(
                          'text-xs',
                          'text-text-muted',
                          'dark:text-stone-400',
                          'mb-1'
                        )}
                      >
                        {co2SavingsLabel}
                      </p>
                      <p className={cn('font-semibold', 'text-success')}>
                        {formatNumber(material.co2SavingsKG)} kg
                      </p>
                    </div>
                    <div>
                      <p
                        className={cn(
                          'text-xs',
                          'text-text-muted',
                          'dark:text-stone-400',
                          'mb-1'
                        )}
                      >
                        {waterSavingsLabel}
                      </p>
                      <p className={cn('font-semibold', 'text-info')}>
                        {formatNumber(material.waterSavingsLT)} L
                      </p>
                    </div>
                  </div>

                  {/* Progress bar for percentage */}
                  <div
                    className={cn(
                      'mt-3',
                      'h-2',
                      'bg-neutral/10',
                      'dark:bg-stone-700',
                      'rounded-full',
                      'overflow-hidden'
                    )}
                  >
                    <div
                      className="h-full bg-primary rounded-full transition-all duration-500"
                      style={{ width: `${material.percentage}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Info Footer */}
        <div
          className={cn(
            'bg-primary/5',
            'dark:bg-primary/10',
            'rounded-lg',
            'p-4',
            'text-sm',
            'text-text-secondary',
            'dark:text-stone-300'
          )}
        >
          <p className={cn('flex', 'items-start', 'gap-2')}>
            <Info
              className={cn(
                'w-4',
                'h-4',
                'mt-0.5',
                'text-primary',
                'flex-shrink-0'
              )}
            />
            <span>{infoText}</span>
          </p>
        </div>
      </div>
    </Modal>
  );
}
