// Subscription Plans
export enum PersonSubscriptionPlan {
  FREEMIUM = 'FREEMIUM',
  BASIC = 'BASIC',
  ADVANCED = 'ADVANCED',
}

export type BusinessSubscriptionPlan =
  | 'FREEMIUM'
  | 'STARTUP'
  | 'BASIC'
  | 'ADVANCED'
  | 'EXPERT';

// Admin Types and Roles
export type AdminType = 'PLATFORM' | 'BUSINESS';

export type AdminRole =
  | 'SUPER_ADMIN'
  | 'MODERATOR'
  | 'CONTENT_MANAGER'
  | 'SUPPORT'
  | 'BUSINESS_OWNER'
  | 'BUSINESS_MANAGER'
  | 'BUSINESS_ANALYST'
  | 'BUSINESS_SUPPORT';

export type AdminPermission =
  | 'MANAGE_PRODUCTS'
  | 'APPROVE_PRODUCTS'
  | 'DELETE_PRODUCTS'
  | 'WRITE_BLOG'
  | 'PUBLISH_BLOG'
  | 'DELETE_BLOG'
  | 'MODERATE_CONTENT'
  | 'MANAGE_USERS'
  | 'BAN_USERS'
  | 'VIEW_USER_DATA'
  | 'MANAGE_ORDERS'
  | 'PROCESS_REFUNDS'
  | 'VIEW_TRANSACTIONS'
  | 'VIEW_ANALYTICS'
  | 'EXPORT_DATA'
  | 'MANAGE_ADMINS'
  | 'MANAGE_CATEGORIES'
  | 'MANAGE_SETTINGS'
  | 'VIEW_SYSTEM_LOGS'
  | 'MANAGE_BUSINESS_PROFILE'
  | 'MANAGE_BUSINESS_TEAM'
  | 'VIEW_BUSINESS_ANALYTICS'
  | 'MANAGE_BUSINESS_PRODUCTS'
  | 'MANAGE_BUSINESS_ORDERS';

// Seller Types
export enum SellerType {
  PERSON = 'PERSON',
  STARTUP = 'STARTUP',
  COMPANY = 'COMPANY',
}

// Business Types
export enum BusinessType {
  RETAIL = 'RETAIL',
  SERVICES = 'SERVICES',
  MIXED = 'MIXED',
}

export enum BusinessFormalizationStatus {
  NOT_REQUIRED = 'NOT_REQUIRED',
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  FORMALIZED = 'FORMALIZED',
}

// Product Related
export enum ProductCondition {
  NEW = 'NEW',
  OPEN_BOX = 'OPEN_BOX',
  LIKE_NEW = 'LIKE_NEW',
  FAIR = 'FAIR',
  POOR = 'POOR',
  FOR_PARTS = 'FOR_PARTS',
  REFURBISHED = 'REFURBISHED',
}

export enum ProductSize {
  XS = 'XS',
  S = 'S',
  M = 'M',
  L = 'L',
  XL = 'XL',
}

export enum Badge {
  POPULAR = 'POPULAR',
  DISCOUNTED = 'DISCOUNTED',
  WOMAN_OWNED = 'WOMAN_OWNED',
  BEST_SELLER = 'BEST_SELLER',
  TOP_RATED = 'TOP_RATED',
  COMMUNITY_FAVORITE = 'COMMUNITY_FAVORITE',
  LIMITED_TIME_OFFER = 'LIMITED_TIME_OFFER',
  FLASH_SALE = 'FLASH_SALE',
  BEST_VALUE = 'BEST_VALUE',
  HANDMADE = 'HANDMADE',
  SUSTAINABLE = 'SUSTAINABLE',
  SUPPORTS_CAUSE = 'SUPPORTS_CAUSE',
  FAMILY_BUSINESS = 'FAMILY_BUSINESS',
  CHARITY_SUPPORT = 'CHARITY_SUPPORT',
  LIMITED_STOCK = 'LIMITED_STOCK',
  SEASONAL = 'SEASONAL',
  FREE_SHIPPING = 'FREE_SHIPPING',
  FOR_REPAIR = 'FOR_REPAIR',
  REFURBISHED = 'REFURBISHED',
  EXCHANGEABLE = 'EXCHANGEABLE',
  LAST_PRICE = 'LAST_PRICE',
  FOR_GIFT = 'FOR_GIFT',
  OPEN_TO_OFFERS = 'OPEN_TO_OFFERS',
  OPEN_BOX = 'OPEN_BOX',
  CRUELTY_FREE = 'CRUELTY_FREE',
  DELIVERED_TO_HOME = 'DELIVERED_TO_HOME',
  IN_HOUSE_PICKUP = 'IN_HOUSE_PICKUP',
  IN_MID_POINT_PICKUP = 'IN_MID_POINT_PICKUP',
}

// Transaction Related
export enum TransactionKind {
  PURCHASE = 'PURCHASE',
  SELL = 'SELL',
  STOREPURCHASE = 'STOREPURCHASE',
  EXCHANGE = 'EXCHANGE',
  RECYCLE = 'RECYCLE',
  REPAIR = 'REPAIR',
  ATTENDTOWORKSHOP = 'ATTENDTOWORKSHOP',
  ATTENDTOEVENT = 'ATTENDTOEVENT',
}

export enum ExchangeStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

// Payment Related
export enum ChileanPaymentProvider {
  KHIPU = 'KHIPU',
  WEBPAY = 'WEBPAY',
}

export enum PaymentEnvironment {
  SANDBOX = 'SANDBOX',
  PRODUCTION = 'PRODUCTION',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  EXPIRED = 'EXPIRED',
}

export enum PaymentType {
  ORDER = 'ORDER',
  QUOTATION = 'QUOTATION',
}

export enum RefundStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

// Service Related
export enum ServicePricing {
  FIXED = 'FIXED',
  QUOTATION = 'QUOTATION',
  HOURLY = 'HOURLY',
  PACKAGE = 'PACKAGE',
}

export enum QuotationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

// Shipping and Orders
export enum ShippingStage {
  PREPARING = 'PREPARING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  RETURNED = 'RETURNED',
  CANCELED = 'CANCELED',
}

// Contact and Communication
export enum ContactMethod {
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
  PHONE = 'PHONE',
  INSTAGRAM = 'INSTAGRAM',
  FACEBOOK = 'FACEBOOK',
  WEBSITE = 'WEBSITE',
  TIKTOK = 'TIKTOK',
}

// Notifications
export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum NotificationType {
  ORDER_RECEIVED = 'ORDER_RECEIVED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  QUOTATION_REQUEST = 'QUOTATION_REQUEST',
  QUOTATION_RECEIVED = 'QUOTATION_RECEIVED',
  QUOTATION_ACCEPTED = 'QUOTATION_ACCEPTED',
  QUOTATION_DECLINED = 'QUOTATION_DECLINED',
  EXCHANGE_PROPOSAL = 'EXCHANGE_PROPOSAL',
  EXCHANGE_ACCEPTED = 'EXCHANGE_ACCEPTED',
  EXCHANGE_DECLINED = 'EXCHANGE_DECLINED',
  EXCHANGE_COMPLETED = 'EXCHANGE_COMPLETED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  PRODUCT_LIKED = 'PRODUCT_LIKED',
  PRODUCT_COMMENTED = 'PRODUCT_COMMENTED',
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
  ACCOUNT_VERIFICATION = 'ACCOUNT_VERIFICATION',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
}

// Blog Related
export enum BlogType {
  RECYCLING = 'RECYCLING',
  POLLUTION = 'POLLUTION',
  SUSTAINABILITY = 'SUSTAINABILITY',
  CIRCULAR_ECONOMY = 'CIRCULAR_ECONOMY',
  USED_PRODUCTS = 'USED_PRODUCTS',
  REUSE = 'REUSE',
  ENVIRONMENT = 'ENVIRONMENT',
  UPCYCLING = 'UPCYCLING',
  RESPONSIBLE_CONSUMPTION = 'RESPONSIBLE_CONSUMPTION',
  ECO_TIPS = 'ECO_TIPS',
  ENVIRONMENTAL_IMPACT = 'ENVIRONMENTAL_IMPACT',
  SUSTAINABLE_LIVING = 'SUSTAINABLE_LIVING',
  OTHER = 'OTHER',
  SECURITY = 'SECURITY',
}

export enum BlogReactionType {
  LIKE = 'LIKE',
  DISLIKE = 'DISLIKE',
}

// Measurements
export enum WeightUnit {
  KG = 'KG',
  LB = 'LB',
  OZ = 'OZ',
  G = 'G',
}

// Legacy support - keeping enum for backward compatibility
export enum BlogCategory {
  RECYCLING = 'RECYCLING',
  POLLUTION = 'POLLUTION',
  SUSTAINABILITY = 'SUSTAINABILITY',
  CIRCULAR_ECONOMY = 'CIRCULAR_ECONOMY',
  USED_PRODUCTS = 'USED_PRODUCTS',
  REUSE = 'REUSE',
  ENVIRONMENT = 'ENVIRONMENT',
  UPCYCLING = 'UPCYCLING',
  RESPONSIBLE_CONSUMPTION = 'RESPONSIBLE_CONSUMPTION',
  ECO_TIPS = 'ECO_TIPS',
  ENVIRONMENTAL_IMPACT = 'ENVIRONMENTAL_IMPACT',
  SUSTAINABLE_LIVING = 'SUSTAINABLE_LIVING',
  OTHER = 'OTHER',
}
